---

- name: Netatalk | Update APT sources
  become: true
  apt:
    update_cache=yes

- name: Netatalk | Install depdendencies
  become: true
  apt:
    name={{ item }}
    state=latest
  with_items:
    - build-essential
    - libevent-dev #(used by netatalk(8))
    - libssl-dev # (DHX auth aka DHCAST128)
    - libgcrypt-dev # (DHX2 auth)
    - libkrb5-dev # (Kerberos V auth)
    - libpam0g-dev #(PAM)
    - libwrap0-dev # (TCP Wrapper)
    - libdb-dev # (dbd CNID backend)
    - libtdb-dev # (tdb CNID backend)
    - libmysqlclient-dev #(mysql CNID backend)
    - avahi-daemon #(Bonjour support)
    - libavahi-client-dev #(Bonjour support)
    - libacl1-dev #(ACL support)
    - libldap2-dev #(enhanced ACL support)
    - libcrack2-dev #(password ckeck)
    - systemtap-sdt-dev #(DTrace-compatible)
    - libdbus-1-dev #(used by afpstats command)
    - libdbus-glib-1-dev #(used by afpstats command)
    - libglib2.0-dev # (used by afpstats command)
    - libio-socket-inet6-perl #(used by asip-status.pl command)
    - tracker #(used for spotlight indexing)
    - libtracker-sparql-1.0-dev #(used for spotlight indexing) (version number may differ)
    - libtracker-miner-1.0-dev #(used for spotlight indexing) (version number may differ)
